### ISSUE TITLE
Call a Connection directly 

### ISSUE THREAD

**Issue by goofy79** [GreenRover/guacamole-auth-userfiles#1]
Hello,
first of all - great job !
It functions without problems. The only thing i need, is to call a connection directly.
For example 
/guacamole/#/?username=mst_henh&ident=1337&connection=RDP

is it possible with this auth plugin ?

**Comment by GreenRover** [comment]
Hello, i improved the example script to show you how it will work.

Please see:
https://github.com/GreenRover/guacamole-auth-userfiles/blob/master/src/example/php/simple_example.php

```
echo $configs->getLink('1337', 'mst_henh', true, 'TestVm RDP');
```

"TestVm RDP" is the name of the connection.

**Comment by GreenRover** [comment]
Is this working for you?
