### ISSUE TITLE
Difficulties of configurations

### ISSUE THREAD

**Issue by ricardodavidsoares** [GreenRover/guacamole-auth-userfiles#2]
Hii,
thank you for developing this. I have several days trying to set it up, but I'm having some difficulties.
I followed all the steps, but, in my PHP script, I'm not storing the user config file generated into GUACAMOLE_HOME (/etc/guacamole), because it gives me a permission error. So I wanted to know if this can be the cause for it not to work and, if possible, another possible causes.
Thank you in advance.

Best regards,
Ricardo Soares.

**Comment by GreenRover** [comment]
Yes this is the problem. The example php code only creates configs for guacamole.
These configs needs to be in GUACAMOLE_HOME (/etc/guacamole).

You have to permitted the php script to write to GUACAMOLE_HOME

I add following to documentation:

An [example PHP implementation](https://github.com/GreenRover/guacamole-auth-userfiles/blob/master/src/example/php/simple_example.php) is included in `src/example/php`.

You will need to give this script the permissions to write to the GUACAMOLE_HOME.

For the most enviroments you should do thinks like this.
`chmod g+w /etc/guacamole`
`useradd -G guacd www-data`

**Comment by ricardodavidsoares** [comment]
Thank you for your quick reply. I really appreciate it.
I tried your suggestion, but when I do "useradd -G guacd www-data" I get the message "useradd -G guacd www-data useradd: the group 'guacd' doesn't exist", and in my apache2/error.log I get:
"PHP Fatal error:  Uncaught exception 'Guacamole_Config_Exception' with message 'Unable to write file "/etc/guacamole/(...)noauth-config.xml".' in /var/www/(...)/Guacamole/Config.php:278\nStack trace:\n#0 /var/www/(...)/Guacamole/Config.php(323): Guacamole_Config->writeConfig(...)\n#1 /var/www/(...): Guacamole_Config->getLink(...)\n#2 {main}\n  thrown in /var/www/(...)/Guacamole/Config.php on line 278"

I'm sorry to bother you with this, but I really need a light. Been working on this for days...

**Comment by GreenRover** [comment]
Ok it seams you have nno idea of linux administration.
I dont want to teach it to you.

Following should make it work but is a securety problem:
`chmod 777 /etc/guacamole`

**Comment by ricardodavidsoares** [comment]
Thank you again.
You're right, I'm web developer beginner and I don't understand much of linux. I'm having a small contact with it as try to set this up.
I understand that you don't have to teach nothing about this, but I don't want to expose my server too. I'm interest to learn, so I just wanted to ask if you could give a advice or something to look for to understand why the first solution doesn't work for me or, if it isn't asking too much, a solution that doesn't create a security problem.

Best regards.

**Comment by GreenRover** [comment]
The php script in your case probaly the apache webserver needs to be able to write to the folder.
So give the linux user group the permission to write and add the user of websever (most www-data) to the owner group of /etc/guacamole. You can find out by using `ls -lA /etc/guacamole`

**Comment by ricardodavidsoares** [comment]
Ok. Thank you for the help.
Even though it isn't safe I made "chmod 777 /etc/guacamole". Now I don't have the permissions error, but I still can't connect. Connection reaches timeout. I don't get any errors in tomcat or apache.
Any clues?

**Comment by ricardodavidsoares** [comment]
As described in the Guacamole manual, "the structure of GUACAMOLE_HOME is rigorously defined, and consists of the following optional files: guacamole.properties, logback.xml, extensions/, lib/" (http://guac-dev.org/doc/gug/configuring-guacamole.html#webapp-logging) but in the company I'm working now the latest version of guacamole they used was 0.8.3, and I guess the structure of directories were diferent, because it used to work and their GUACAMOLE_HOME just had "guacamole.properties". They used to place the plugins in "/var/lib/guacamole/classpath".
I just saw this now and I'm wondering if it's another cause of the problem.

**Comment by GreenRover** [comment]
Here some code from my *.deb file builder (ubuntu 14.04).  It is untested but should compile and setup guacamole. prety god

``` bash
# Prepare
export LANG=C
export LC_ALL=C
export LANGUAGE=C
sudo mkdir -m 777 /srv/guacamole/
sudo mkdir -m 777 /srv/guacamole/deb/

# Remove old deb files.
rm /srv/guacamole/deb/*.deb

# Prepare env
sudo apt-get update
sudo apt-get install -y \
  libossp-uuid-dev \
  libssh2-1-dev \
  libpango1.0-dev \
  libfreerdp-dev \
  libvncserver-dev \
  libssl-dev \
  libtelnet-dev \
  maven \
  checkinstall \
  libtool \
  libcairo2-dev \
  libjpeg-turbo8-dev \
  libjpeg62-dev \
  libpng12-dev \
  libossp-uuid-dev \
  libvorbis-dev \
  libwebp-dev \
  default-jdk \
  tomcat7

sudo apt-get build-dep guacd -y


if [ ! -d "/srv/guacamole/guacd/" ]; then
  # clone guacd if required
  git clone https://github.com/glyptodon/guacamole-server.git /srv/guacamole/guacd/
fi

cd /srv/guacamole/guacd/
# Update guacd
## Delete all old files, guacd seas not to clean up well.
sudo find /srv/guacamole/guacd/ -mindepth 1 -maxdepth 1 \( ! -iname ".git*" \) -exec rm -rf {} \;
git checkout  -q master
git reset -q HEAD --hard
git clean -fq
git pull
git submodule init
git submodule update
make clean || true

# Compile guacd
if [ ! -f "./configure" ]; then
  autoreconf -fi
fi

./configure \
  '--with-init-dir=/etc/init.d' \
  '--with-rdp' \
  '--with-vnc' \
  '--with-ssh' \
  '--with-ssl' \
  '--with-guacd-conf=/etc/guacamole/guacd.conf' \
  '--prefix=/usr/local/guacamole'

make -j 8

sudo groupadd -fr "guacd" 

# Create guacd user if it does not exist
sudo useradd -g "guacd" -d "/usr/local/guacamole/share" -s /bin/false -r "guacd"

sudo chown guacd:guacd /usr/local/guacamole/share
sudo chmod 700 /usr/local/guacamole/share

sudo mkdir -p /etc/guacamole/
sudo chmod 777 /etc/guacamole/

sudo make install

sudo ldconfig

sudo ln -s /usr/local/guacamole/lib/freerdp/* /usr/lib/x86_64-linux-gnu/freerdp/ || true

sudo update-rc.d guacd defaults





SERVER_VERSION="tomcat7"

# Build client
if [ ! -d "/srv/guacamole/client_$SERVER_VERSION/" ]; then
  # clone client if required
  git clone git://github.com/glyptodon/guacamole-client.git /srv/guacamole/client_$SERVER_VERSION/
fi

cd /srv/guacamole/client_$SERVER_VERSION/

sudo find /srv/guacamole/client_$SERVER_VERSION/ -mindepth 1 -maxdepth 1 \( ! -iname ".git*" \) -exec rm -rf {} \;
git checkout  -q master
git reset -q HEAD --hard
git clean -fq
git pull
git submodule init
git submodule update
make clean || true

# Compile
mvn package





# Build uth-userfiles
if [ ! -d "/srv/guacamole/auth-userfiles/" ]; then
  # clone uth-userfiles if required
  git clone https://github.com/GreenRover/guacamole-auth-userfiles.git /srv/guacamole/auth-userfiles/
fi

cd /srv/guacamole/auth-userfiles/

# Update uth-userfiles
## Delete all old files, guacd seas not to clean up well.
sudo find /srv/guacamole/auth-userfiles/ -mindepth 1 -maxdepth 1 \( ! -iname ".git*" \) -exec rm -rf {} \;
git checkout  -q master
git reset -q HEAD --hard
git clean -fq
git pull
git submodule init
git submodule update
make clean || true

# Compile
mvn package







# Install
sudo mkdir -p /var/lib/guacamole/lib
sudo mkdir -p /var/lib/guacamole/extensions

cp /srv/guacamole/client_$SERVER_VERSION/guacamole/target/guacamole-*.war /var/lib/guacamole/

# Add war file.
cp /srv/guacamole/client_$SERVER_VERSION/guacamole/target/guacamole-*.war /var/lib/guacamole/
mkdir -p /var/lib/$SERVER_VERSION/webapps
find /var/lib/guacamole/ -iname "guacamole-*.war" -execdir ln -s  /var/lib/guacamole/{} /var/lib/$SERVER_VERSION/webapps/guacamole.war \;

# Add default extensions.
find /srv/guacamole/client_$SERVER_VERSION/extensions/ -iname "*.jar" -execdir cp {} /var/lib/guacamole/extensions/{} \;

# Build mst extensions.
cp /srv/guacamole/auth-userfiles/target/guacamole-*.jar /var/lib/guacamole/extensions/


sudo cat << EOF > /etc/guacamole/guacamole.propertie
lib-directory: /var/lib/tomcat7/webapps/guacamole/WEB-INF/classes

# Hostname and port of guacamole proxy
guacd-hostname: localhost
guacd-port:     4822

# Auth provider class (authenticates user/pass combination, needed if using the provided login screen)
# auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
# auth-provider: net.sourceforge.guacamole.net.auth.mysql.MySQLAuthenticationProvider
# auth-provider: net.sourceforge.guacamole.net.auth.noauth.NoAuthenticationProvider
# auth-provider: com.stephensugden.guacamole.net.hmac.HmacAuthenticationProvider
auth-provider: net.sourceforge.guacamole.net.auth.userfiles.UserFilesAuthenticationProvider

## basic
# basic-user-mapping: /etc/guacamole/user-mapping.xml

## mysql
# mysql-hostname: localhost
# mysql-port: 3306
# mysql-database: guacamole
# mysql-username: guacamole
# mysql-password: guacamole

## hmac
# secret-key: Somorp15
# timestamp-age-limit: 600000
EOF

sudo ln -s /etc/guacamole/extensions /var/lib/guacamole/extensions
sudo ln -s /etc/guacamole/lib /var/lib/guacamole/lib
```

**Comment by ricardodavidsoares** [comment]
Hello,
thanks again for puting the effort to try to help me.
I didn't run all the script because I've already had guacd and guacamole-client on versions 0.9.8. My guacd doens't report any error and succeeds on start, so I guess everything is OK. I already had downloaded guacamole-client from source (http://sourceforge.net/projects/guacamole/files/current/binary/) and placed it at "/var/lib/tomcat7/webapps". Once I restarted tomcat it created the respective directory.

So I tried to check what was new from your script, and I ended up creating the directories "/var/lib/guacamole/extensions" and "/var/lib/guacamole/lib", placed all .jar files on "extensions" and then I created a "sl" for the directories on GUACAMOLE_HOME (/etc/guacamole).
After this I procceeded to update "guacamole.properties". On this step, when I went to set "lib-directory" I check that folder to see what was in it. I figured out that on "/var/lib/tomcat7/webapps/guacamole/WEB-INF/classes/net/sourceforge/guacamole/net" I have just another directory, named "basic", that has BasicFileAuthenticationProvider's. I don't know if this is revelant or normal, I just wanted to point it.

At the end I got the same results, it didn't work :( Maybe I missed something. I still get conection timeout and no error at log files.
Sorry for being so dumb, but I still can't get this to work. I don't have any ideia of what to do...

**Comment by GreenRover** [comment]
Place a file called `logback.xml`

in `/etc/guacamole/logback.xml`

and add this content:
http://guac-dev.org/doc/gug/configuring-guacamole.html#webapp-logging

Then stop the deamons
`service guacd stop`
`service tomcat7 stop`

clear the logs
`echo "" > /var/log/tomcat7/catalina.out` 
`echo "" > /var/log/guacamole.log` 

start the deamons.
`service guacd start`
`service tomcat7 start`

Try to open a link / conntet to RDP or whatever.

The post the content of the logs.
http://pastebin.com/

**Comment by ricardodavidsoares** [comment]
Ok. Just did it. I never used that, I made a paste and this is the url http://pastebin.com/index/JMUWmHaF
If I made it wrong let me know, please.

**Comment by GreenRover** [comment]
Its seams you have not activated debug mode.

It should lokk like this for you:

``` bash
cat /etc/guacamole/logback.xml 
<configuration>

    <!-- Appender for debugging -->
    <appender name="GUAC-DEBUG" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <!-- Log at DEBUG level -->
    <root level="debug">
        <appender-ref ref="GUAC-DEBUG"/>
    </root>

</configuration>
```

To be shure to additionaly this:

``` bash
echo "" >> /etc/default/tomcat7
echo "GUACAMOLE_HOME=/etc/guacamole" >> /etc/default/tomcat7
```

Restart tomcat

``` bash
service restart tomcat7
```

Then you should find a line like this in your `/var/log/tomcat7/catalina.out`

```
13:14:02.432 [localhost-startStop-1] DEBUG o.g.g.n.b.extension.ExtensionModule - Error reading authentication provider from guacamole.properties.

.....

13:14:02.742 [localhost-startStop-1] DEBUG o.g.g.n.b.extension.ExtensionModule - Loading extension: "guacamole-auth-userfiles-0.9.8.jar"
```

**Comment by ricardodavidsoares** [comment]
Hii,
my logback.xml file looks just like the one you posted. I had already added this line "GUACAMOLE_HOME=/etc/guacamole" to "/etc/default/tomcat7".
But when I make "service tomcat7 restart" I keep geting the same errors (http://pastebin.com/index/JMUWmHaF) on "catalina.out". One of them is:

_SEVERE: One or more Filters failed to start. Full details will be found in the appropriate container log file
Nov 25, 2015 12:31:55 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/guacamole] startup failed due to previous errors_

Once again thank you for time...

**Comment by GreenRover** [comment]
Sorry but this is not a problem of my plugin, you tomcat is not running.

An have a look at the container log file!

`/var/log/tomcat7/localhost.2015-11-25.log`

**Comment by ricardodavidsoares** [comment]
Ok. Thank you for the explanation.
Here's my _/var/log/tomcat7/localhost.2015-11-25.log_ http://pastebin.com/nph5etLg in case you still available to help.
It would be much appreciated...

**Comment by GreenRover** [comment]
Your guacamole installations is incomplete, try to compile by your own using my script from above.
