### ISSUE TITLE
Username does not allow . (dot)

### ISSUE THREAD

**Issue by fdellwing** [GreenRover/guacamole-auth-userfiles#5]
Hey,

do you remember why you choose these regexp like you did?

https://github.com/GreenRover/guacamole-auth-userfiles/blob/f33bbe61a697fc58201f8933f7612443fd3ec5ce/src/example/php/library/Guacamole/Config.php#L265-L267

https://github.com/GreenRover/guacamole-auth-userfiles/blob/f33bbe61a697fc58201f8933f7612443fd3ec5ce/src/main/java/net/sourceforge/guacamole/net/auth/userfiles/UserFilesAuthenticationProvider.java#L193-L196

We have some problems because we allow dots in the username.

There is nothing in RDP/VNC that prohibits a dot in the username. Linux file structure will also not break from a file that contains multiple dots.

Can we just add a dot to the regexp or do you remember/see any problems with that?

Best regards
Fabian

**Comment by GreenRover** [comment]
If you allow dots in file name.
Your username could be.

user/../../../../etc/passwd

to do evil things.

You need to prevent this

**Comment by fdellwing** [comment]
Of course, that is logical. But we do not allow `/` in usernames and your regexp also does not allow it.

And while `.` is a quite common character in a username, `/` is not.

We will change this in our version of the plugin, would you like this change also upstream?

**Comment by GreenRover** [comment]
Yes please give it upstream

**Comment by fdellwing** [comment]
Sure will make it available to you. We also updated it to 1.4.0 (no real changes needed). Will make another PR for that.
